version: 2
jobs:
  deploy:
    working_directory: ~/mandarin-landing-page
    docker:
      - image: circleci/node:8.14
    steps:
      - checkout
      # Restore npm cache
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      # Run tests
      - run:
          name: Run tests
          command: yarn test

      # Persist npm cache
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - persist_to_workspace:
          root: ~/mandarin-landing-page
          paths: .

      - run:
          name: Deploy update to Surge
          command: |
            yarn build
            yarn deploy
workflows:
  version: 2
  test_and_deploy_update:
    jobs:
      - deploy
